name: Deploy To Azure Web App

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout Surce
        uese: action/chekout@v3
      - name: Setup node.js version
        uses: action/setup-node@v4
        with: 
          node-version: '20.x'
      - name: Instal Dependences
        run: cd NovaAplicacao && npm install
      - name: Deploy on Azure
        uses: azure/webapp-deploy@v2
        with:
          app-name: 'RecursoWeb'
          publish-profile: '${{secrets.AZURE_PUBLISH_PROFILE}}'
          packege: ,/NovaAplicacao